version: '3.7'

services:
    db:
        image: postgres:13.0
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./db.env


    affi:
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile.dev
        container_name: affi
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - ./staticfiles:/home/app/web/staticfiles 
            - ./mediafiles:/home/app/web/mediafiles
            - .:/home/app/web/
            - ./db.sqlite3:/home/app/web/db.sqlite3/
        env_file:
            - ./.env.dev
        depends_on:
            - redis
            - db
        

    redis:
        build:
            context: ./redis/
            dockerfile: Dockerfile.dev
        container_name: redis
        ports:
            - "6379:6379"

    
    celery:
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile.dev
        command: celery -A affi worker --loglevel=debug --concurrency=8
        volumes:
            - ./mediafiles:/home/app/web/mediafiles
            - .:/home/app/web
        depends_on:
            - redis
        env_file:
            - ./.env.dev

    
    nginx:
        build:
            context: ./nginx/
            dockerfile: Dockerfile.dev
        container_name: nginx
        restart: always
        volumes:
            - ./mediafiles:/home/app/web/mediafiles
            - ./staticfiles:/home/app/web/staticfiles 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - 80:80
            - 443:443
        env_file:
            - ./db.env
        depends_on:
            - affi

    
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
            - ./mediafiles:/home/app/web/mediafiles
            - ./staticfiles:/home/app/web/staticfiles 

    

volumes:
    static_volume:
    media_files:
    postgres_data:
