FROM python:3.8.5-alpine

# create directory for the app user
RUN mkdir -p /home/app

# create the appropriate directories
# ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1 

# copy requirement to image
COPY ./requirements.txt $APP_HOME

WORKDIR $APP_HOME

# install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
# RUN apk add postgresql
# RUN apk add postgresql-dev
# RUN pip install psycopg2

COPY . $APP_HOME