version: '3.7'

services:
    affi:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        container_name: affi
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"

        ports:
            - "8000:8000"
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_files:/home/app/web/mediafiles
            - .:/home/app/web/
            - /data/db.sqlite3:/home/app/web/db.sqlite3/
            

volumes:
    static_volume:
    media_files:
