# Generated by Django 3.2.7 on 2021-09-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_name',
        ),
    ]
