# Generated by Django 3.2.7 on 2021-10-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0005_auto_20211011_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('affiliation_url', models.URLField(blank=True, null=True)),
                ('affiliator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.aff')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'unique_together': {('affiliator', 'related_product')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('base_order_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], default='success', max_length=50)),
                ('related_affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliation.affiliation')),
            ],
        ),
    ]
