# Generated by Django 3.2.7 on 2021-09-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('deposit', 'deposit'), ('RECEIVED', 'RECEIVED')], max_length=50)),
                ('transaction_state', models.CharField(choices=[('deposit', 'deposit'), ('RECEIVED', 'RECEIVED')], default='pending', max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.wallet')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial.wallet')),
            ],
        ),
    ]
