# Generated by Django 3.2.7 on 2021-10-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_state',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
