# Generated by Django 3.2.7 on 2021-09-29 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210929_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate_rate',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
