# Generated by Django 3.2.7 on 2021-09-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_rating'),
        ('product', '0003_product_affiliate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop'),
        ),
    ]
