# Generated by Django 3.2.7 on 2021-09-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_related_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='related_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='product.product'),
        ),
    ]
