# Generated by Django 3.2.7 on 2021-10-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_dimension_related_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(blank=True, default='product/default_product_pic.png', upload_to=None),
        ),
    ]
