# Generated by Django 3.2.7 on 2021-10-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20211003_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
