# Generated by Django 3.2.7 on 2021-10-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
