# Generated by Django 3.2.7 on 2021-10-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_price_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
