# Generated by Django 3.2.7 on 2021-10-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='metadata',
            new_name='meta_data',
        ),
    ]
