# Generated by Django 3.2.7 on 2021-10-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_metadata_product_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog_visibility',
            field=models.CharField(choices=[('visible', 'visible'), ('catalog', 'catalog'), ('search', 'search'), ('hidden', 'hidden')], default='visible', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'draft'), ('pending', 'pending'), ('private', 'private'), ('publish', 'publish')], default='publish', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('instock', 'instock'), ('outofstock', 'outofstock'), ('onbackorder', 'onbackorder')], default='instock', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_status',
            field=models.CharField(choices=[('taxable', 'taxable'), ('shipping', 'shipping'), ('none', 'none')], default='taxable', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('simple', 'simple'), ('grounded', 'grounded'), ('external', 'external'), ('variable', 'variable')], default='simple', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('hold', 'hold'), ('spam', 'spam'), ('unspam', 'unspam'), ('trash', 'trash'), ('untrash', 'untrash')], default='approved', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
