# Generated by Django 3.2.7 on 2021-10-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
