# Generated by Django 3.2.7 on 2021-10-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211002_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='aff',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aff',
            name='national_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aff',
            name='profile_pic',
            field=models.ImageField(default='profile/default_profile_pic.png', upload_to='profile/'),
        ),
    ]
