# Generated by Django 3.2.7 on 2021-10-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211002_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aff',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
