# Generated by Django 3.2.7 on 2021-10-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_aff_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aff',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='aff',
            name='profile_pic',
        ),
    ]
