# Generated by Django 3.2.7 on 2021-10-05 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_aff_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aff',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
