# Generated by Django 3.2.7 on 2021-10-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211005_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aff',
            name='uuid',
        ),
    ]
