# Generated by Django 3.2.7 on 2021-09-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('src', models.ImageField(blank=True, upload_to='shop/')),
                ('alt', models.CharField(blank=True, max_length=50)),
                ('related_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.shop')),
            ],
        ),
    ]
