# Generated by Django 3.2.7 on 2021-10-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopimage',
            name='src',
            field=models.ImageField(default='shop/default_shop_pic.png', upload_to='shop/'),
        ),
    ]
