# Generated by Django 3.2.7 on 2021-10-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shopimage_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='profile_pic',
            field=models.ImageField(default='profile/default_shop_pic.png', upload_to='profile/'),
        ),
    ]
