# Generated by Django 3.2.7 on 2021-10-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='profile_pic',
            new_name='shop_pic',
        ),
        migrations.DeleteModel(
            name='ShopImage',
        ),
    ]
