# Generated by Django 3.2.7 on 2021-10-02 11:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_aff_age'),
        ('shop', '0006_auto_20211002_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Aff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.aff')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
