# Generated by Django 3.2.7 on 2021-10-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_aff_age'),
        ('shop', '0007_shoprate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoprate',
            old_name='Aff',
            new_name='aff',
        ),
        migrations.AlterUniqueTogether(
            name='shoprate',
            unique_together={('aff', 'shop')},
        ),
    ]
