# Generated by Django 3.2.7 on 2021-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_shop_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_pic',
            field=models.ImageField(default='profile/default_shop_pic.jpeg', upload_to='profile/'),
        ),
    ]
