# Generated by Django 3.2.7 on 2021-10-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_shop_shop_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='is_verified',
            new_name='is_staff',
        ),
    ]
