# Generated by Django 3.2.7 on 2021-10-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_is_verified_shop_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='api_cunsumer_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='api_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='data_ready',
            field=models.BooleanField(default=False),
        ),
    ]
