# Generated by Django 3.2.7 on 2021-10-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211010_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='name',
        ),
    ]
